// contract: each primitive's ID starts at zero within its instance, including the interior primitives of adjacency
// topologies. "PrimitiveID starts at 0 for the first primitive generated by a Draw*() call, and increments for each
// subsequent primitive. When Draw*Instanced() is used, the PrimitiveID resets to its starting value whenever a new
// instance begins in the set of instances produced by the call." (D3D11.3 8.17). "the PrimitiveID is only maintained
// for the interior primitives in the topology (the non-adjacent primitives), just like the set of primitives in a
// triangle strip without adjacency." (8.17). strip cuts restart assembly, not PrimitiveID (8.6.2 pseudocode).
// every primitive covers one pixel, whose value must be its ID plus one; instances have separate rows. the geometry
// and topology data are those of ../assembly.hpp, with positive cull distances and no stream output.
#include "d3d12_test.hpp"
#include "../assembly.hpp"
#include "../../src/airconv/airconv_public.h"

static const char hlsl[] = R"hlsl(
cbuffer Case : register(b0) { uint corners, strip, stride, first, every, last, primitives, run_vertices; };
struct O {
  float4 pos : SV_Position;
#if CULL
  float cull : SV_CullDistance;
#endif
};
O vs(uint id : SV_VertexID, uint instance : SV_InstanceID) {
  uint run = id / run_vertices;
  id %= run_vertices;
  uint k = strip ? id : id % stride, c = (k - first) / every, n = strip ? c : id / stride;
  bool own = k >= first && (k - first) % every == 0 && (strip ? id <= last : c < corners);
  float2 pixels;
  if (!own)
    pixels = float2(id + 0.5, 2 * instance + 1.5);
  else if (corners == 1)
    pixels = float2(n + 0.5, 2 * instance + 0.5);
  else if (corners == 2)
    pixels = float2(n + (strip ? 0 : c) + 0.25, 2 * instance + 0.5);
  else if (strip)
    pixels = float2(n + 0.5, 2 * instance + (n % 2 ? 0.9 : 0.1));
  else
    pixels = float2(n + (c == 1 ? 1.4 : 0), 2 * instance + (c == 2 ? 1.4 : 0));
  pixels.x += run * primitives;
  O o;
  o.pos = float4(pixels / float2(WIDTH, HEIGHT) * float2(2, -2) + float2(-1, 1), 0, 1);
#if CULL
  o.cull = 1;
#endif
  return o;
}
uint ps(uint id : SV_PrimitiveID) : SV_Target { return id + 1; }
)hlsl";

int main(int argc, char **argv) {
  Compiler compiler;
  if (!front_end(argc, argv, compiler)) {
    printf("skipped: dxcompiler.dll not found\n");
    return 77;
  }
  step("create the device, pipelines and readback target");
  ComPtr<ID3D12Device> device;
  CHECK(D3D12CreateDevice(nullptr, D3D_FEATURE_LEVEL_11_0, IID_PPV_ARGS(&device)));
  const UINT max_instances = 3, width = 4 * SM50_GEOMETRY_WARP_THREADS + 2, height = 2 * max_instances;
  struct Constants {
    UINT corners, strip, stride, first, every, last, primitives, run_vertices;
  };
  D3D12_ROOT_PARAMETER parameter{D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS};
  parameter.Constants.Num32BitValues = sizeof(Constants) / sizeof(UINT);
  auto rs = root_signature(device.Get(), {1, &parameter});
  if (!expect(!!rs, "root signature was not created"))
    return verdict();
  const D3D12_PRIMITIVE_TOPOLOGY_TYPE types[] = {
      D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT, D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE, D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE};
  const DXGI_FORMAT formats[] = {DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16_UINT, DXGI_FORMAT_R32_UINT};
  const D3D12_INDEX_BUFFER_STRIP_CUT_VALUE cut_values[] = {D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_DISABLED,
                                                           D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFF,
                                                           D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFFFFFF};
  ComPtr<ID3D12PipelineState> psos[2][std::size(types)][std::size(formats)];
  auto ps = compiler.compile(hlsl, "ps", "ps",
                             {"WIDTH=" + std::to_string(width), "HEIGHT=" + std::to_string(height), "CULL=0"});
  if (!expect(!ps.empty(), "pixel shader did not compile"))
    return verdict();
  for (bool cull : {false, true}) {
    auto vs = compiler.compile(
        hlsl, "vs", "vs",
        {"WIDTH=" + std::to_string(width), "HEIGHT=" + std::to_string(height), "CULL=" + std::to_string(cull)});
    if (!expect(!vs.empty(), "vertex shader did not compile"))
      return verdict();
    D3D12_GRAPHICS_PIPELINE_STATE_DESC desc{rs.Get(), bytecode(vs), bytecode(ps)};
    desc.BlendState.RenderTarget[0].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;
    desc.SampleMask = ~0u;
    desc.RasterizerState = {D3D12_FILL_MODE_SOLID, D3D12_CULL_MODE_NONE};
    desc.RasterizerState.DepthClipEnable = TRUE;
    desc.NumRenderTargets = 1;
    desc.RTVFormats[0] = DXGI_FORMAT_R32_UINT;
    desc.SampleDesc = {1, 0};
    for (UINT type = 0; type < std::size(types); type++)
      for (UINT f = 0; f < std::size(formats); f++) {
        desc.PrimitiveTopologyType = types[type];
        desc.IBStripCutValue = types[type] == D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT ? cut_values[0] : cut_values[f];
        CHECK(device->CreateGraphicsPipelineState(&desc, IID_PPV_ARGS(&psos[cull][type][f])));
      }
  }
  D3D12_HEAP_PROPERTIES heap{D3D12_HEAP_TYPE_DEFAULT};
  D3D12_RESOURCE_DESC texture_desc{D3D12_RESOURCE_DIMENSION_TEXTURE2D,
                                   0,
                                   width,
                                   height,
                                   1,
                                   1,
                                   DXGI_FORMAT_R32_UINT,
                                   {1, 0},
                                   D3D12_TEXTURE_LAYOUT_UNKNOWN,
                                   D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET};
  ComPtr<ID3D12Resource> target;
  CHECK(device->CreateCommittedResource(&heap, D3D12_HEAP_FLAG_NONE, &texture_desc, D3D12_RESOURCE_STATE_RENDER_TARGET,
                                        nullptr, IID_PPV_ARGS(&target)));
  ComPtr<ID3D12DescriptorHeap> rtvs;
  D3D12_DESCRIPTOR_HEAP_DESC rtv_desc{D3D12_DESCRIPTOR_HEAP_TYPE_RTV, 1};
  CHECK(device->CreateDescriptorHeap(&rtv_desc, IID_PPV_ARGS(&rtvs)));
  auto rtv = rtvs->GetCPUDescriptorHandleForHeapStart();
  device->CreateRenderTargetView(target.Get(), nullptr, rtv);
  D3D12_PLACED_SUBRESOURCE_FOOTPRINT footprint;
  UINT64 bytes;
  device->GetCopyableFootprints(&texture_desc, 0, 1, 0, &footprint, nullptr, nullptr, &bytes);
  auto readback = buffer(device.Get(), D3D12_HEAP_TYPE_READBACK, bytes, D3D12_RESOURCE_STATE_COPY_DEST);
  if (!expect(!!readback, "readback buffer was not created"))
    return verdict();
  ComPtr<ID3D12CommandQueue> queue;
  ComPtr<ID3D12CommandAllocator> allocator;
  ComPtr<ID3D12GraphicsCommandList> list;
  D3D12_COMMAND_QUEUE_DESC queue_desc{D3D12_COMMAND_LIST_TYPE_DIRECT};
  CHECK(device->CreateCommandQueue(&queue_desc, IID_PPV_ARGS(&queue)));
  CHECK(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT, IID_PPV_ARGS(&allocator)));
  CHECK(device->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT, allocator.Get(), nullptr, IID_PPV_ARGS(&list)));
  CHECK(list->Close());
  ComPtr<ID3D12CommandSignature> signatures[2];
  for (bool indexed : {false, true}) {
    D3D12_INDIRECT_ARGUMENT_DESC argument{indexed ? D3D12_INDIRECT_ARGUMENT_TYPE_DRAW_INDEXED
                                                  : D3D12_INDIRECT_ARGUMENT_TYPE_DRAW};
    D3D12_COMMAND_SIGNATURE_DESC desc{
        UINT(indexed ? sizeof(D3D12_DRAW_INDEXED_ARGUMENTS) : sizeof(D3D12_DRAW_ARGUMENTS)), 1, &argument};
    CHECK(device->CreateCommandSignature(&desc, nullptr, IID_PPV_ARGS(&signatures[indexed])));
  }

  for (auto &c : assembly::cases) {
    UINT per_primitive = c.strip ? c.corners * c.every + 2 * c.first : c.stride;
    // the position and optional scalar cull distance fit the full object warp
    auto warp = SM50GeometryWarp(per_primitive, c.strip, 0);
    for (UINT primitives : {3u, warp.primitives - 1, warp.primitives, warp.primitives + 1, 2 * warp.primitives + 1})
      for (bool cull : {false, true})
        for (UINT f = 0; f < std::size(formats); f++)
          for (bool indirect : {false, true})
            for (UINT instances : {1u, max_instances})
              for (bool cuts : {false, true}) {
                bool indexed = formats[f] != DXGI_FORMAT_UNKNOWN;
                if (cuts && (!indexed || !c.strip))
                  continue;
                step("topology %u, %u primitives, cull %u, index format %u, indirect %u, %u instances, cuts %u",
                     c.topology, primitives, cull, formats[f], indirect, instances, cuts);
                UINT vertices = c.strip ? (primitives - 1) * c.every + per_primitive : primitives * c.stride;
                Constants values{c.corners,  c.strip, c.stride,
                                 c.first,    c.every, c.first + (primitives + c.corners - 2) * c.every,
                                 primitives, vertices};
                std::vector<UINT> words;
                UINT cut = formats[f] == DXGI_FORMAT_R16_UINT ? UINT16_MAX : UINT32_MAX;
                if (cuts)
                  words.push_back(cut);
                for (UINT run = 0; run < (cuts ? 2u : 1u); run++) {
                  for (UINT i = 0; i < vertices; i++)
                    words.push_back(run * vertices + i);
                  if (cuts)
                    words.insert(words.end(), {cut, cut});
                }
                UINT count = indexed ? (UINT)words.size() : vertices;
                ComPtr<ID3D12Resource> indices;
                D3D12_INDEX_BUFFER_VIEW view{};
                if (indexed) {
                  std::vector<UINT16> narrow(words.begin(), words.end());
                  UINT size = count * (formats[f] == DXGI_FORMAT_R16_UINT ? sizeof(UINT16) : sizeof(UINT));
                  indices = buffer(device.Get(), D3D12_HEAP_TYPE_UPLOAD, size, D3D12_RESOURCE_STATE_GENERIC_READ);
                  if (!expect(!!indices, "index buffer was not created"))
                    return verdict();
                  void *mapped;
                  CHECK(indices->Map(0, nullptr, &mapped));
                  memcpy(mapped, formats[f] == DXGI_FORMAT_R16_UINT ? (const void *)narrow.data() : words.data(), size);
                  indices->Unmap(0, nullptr);
                  view = {indices->GetGPUVirtualAddress(), size, formats[f]};
                }
                ComPtr<ID3D12Resource> arguments;
                if (indirect) {
                  D3D12_DRAW_ARGUMENTS draw{count, instances};
                  D3D12_DRAW_INDEXED_ARGUMENTS draw_indexed{count, instances};
                  UINT size = indexed ? sizeof(draw_indexed) : sizeof(draw);
                  arguments = buffer(device.Get(), D3D12_HEAP_TYPE_UPLOAD, size, D3D12_RESOURCE_STATE_GENERIC_READ);
                  if (!expect(!!arguments, "indirect buffer was not created"))
                    return verdict();
                  void *mapped;
                  CHECK(arguments->Map(0, nullptr, &mapped));
                  memcpy(mapped, indexed ? (const void *)&draw_indexed : &draw, size);
                  arguments->Unmap(0, nullptr);
                }
                CHECK(forget(readback.Get()));
                CHECK(allocator->Reset());
                CHECK(list->Reset(allocator.Get(), psos[cull][c.corners - 1][f].Get()));
                const float clear[4] = {};
                list->ClearRenderTargetView(rtv, clear, 0, nullptr);
                D3D12_VIEWPORT viewport{0, 0, (float)width, (float)height, 0, 1};
                D3D12_RECT scissor{0, 0, (LONG)width, (LONG)height};
                list->RSSetViewports(1, &viewport);
                list->RSSetScissorRects(1, &scissor);
                list->OMSetRenderTargets(1, &rtv, FALSE, nullptr);
                list->SetGraphicsRootSignature(rs.Get());
                list->SetGraphicsRoot32BitConstants(0, sizeof(values) / sizeof(UINT), &values, 0);
                list->IASetPrimitiveTopology(c.topology);
                list->IASetIndexBuffer(indexed ? &view : nullptr);
                if (indirect)
                  list->ExecuteIndirect(signatures[indexed].Get(), 1, arguments.Get(), 0, nullptr, 0);
                else if (indexed)
                  list->DrawIndexedInstanced(count, instances, 0, 0, 0);
                else
                  list->DrawInstanced(count, instances, 0, 0);
                transition(list.Get(), target.Get(), D3D12_RESOURCE_STATE_RENDER_TARGET,
                           D3D12_RESOURCE_STATE_COPY_SOURCE);
                D3D12_TEXTURE_COPY_LOCATION src{target.Get(), D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX},
                    dst{readback.Get(), D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT};
                dst.PlacedFootprint = footprint;
                list->CopyTextureRegion(&dst, 0, 0, 0, &src, nullptr);
                transition(list.Get(), target.Get(), D3D12_RESOURCE_STATE_COPY_SOURCE,
                           D3D12_RESOURCE_STATE_RENDER_TARGET);
                CHECK(submit(device.Get(), queue.Get(), list.Get()));
                const char *mapped;
                CHECK(readback->Map(0, nullptr, (void **)&mapped));
                for (UINT y = 0; y < height; y++)
                  for (UINT x = 0; x < width; x++) {
                    UINT id = x - (c.strip && c.corners == 3);
                    UINT want = !(y % 2) && y / 2 < instances && id < primitives * (cuts ? 2 : 1) ? id + 1 : 0;
                    UINT got =
                        reinterpret_cast<const UINT *>(mapped + footprint.Offset + y * footprint.Footprint.RowPitch)[x];
                    expect(got == want, "pixel %u,%u: %u, want %u", x, y, got, want);
                  }
                readback->Unmap(0, nullptr);
              }
  }
  return verdict();
}
