// contract: indexed draws with geometry or tessellation read an unbound index buffer as zero and fetch vertex
// BaseVertexLocation for every primitive and instance. "If a Vertex Buffer or Index Buffer is read by the Input
// Assembler, but the slot being read has no Buffer bound, the result of the read is 0 for all expected components."
// (D3D11.3 functional specification, 8.20). BaseVertexLocation is "Which Vertex in each buffer marked as Vertex Data
// to consider as Index "0"." (8.6); IndexCountPerInstance is "How many indices to read sequentially from the Index
// Buffer (same set repeated for each Instance)." (8.6, 8.8). "For DrawIndexed() and DrawIndexedInstanced(), VertexID
// represents the index value." (8.16). StartInstanceLocation is "Which Instance to start sequentially fetching from
// in each Buffer marked as Instance Data." (8.6). "PrimitiveID starts at 0 for the first primitive generated by a
// Draw*() call, and increments for each subsequent primitive." It "resets to its starting value whenever a new
// instance begins" (8.17). "InstanceID starts at 0 for the first instance of vertices generated by a Draw*() call."
// (8.18).
// "DrawIndexed() behaves the same as DrawIndexedInstanced(), with InstanceCount = 1 and StartInstanceLocation = 0."
// (8.5.1).
// "there must be no culling of degenerate primitives until rasterizer setup, so that the Geometry Shader is
// guaranteed to see all geometry." (8.15). "Tri and Quad Domains are tiled with quads, each made of 2 triangles"
// (11.7.6).
// "for a given patch, all of the primitives generated for it have the same PrimitiveID." (11.7.9.1).
// without tessellation, patch topologies "can be fed to the Geometry Shader and/or Stream Output" (8.11).
// "any incomplete primitives are silently discarded." (8.13).
// drawn bound indices are 1; the skipped prefix is 0, so stale bindings and lost offsets change the pixels.
#define INITGUID
#include "d3d11_test.hpp"
#include "../../src/airconv/airconv_public.h"
#include <algorithm>

static const char hlsl[] = R"hlsl(
struct V {
  float4 pos : SV_Position;
  nointerpolation float2 center : CENTER;
  nointerpolation float2 tally : TALLY;
};
V vs(float x : POSITION, float2 data : INSTANCE, uint vertex : SV_VertexID, uint instance : SV_InstanceID) {
  V v;
  v.center = float2(x, data.x);
  v.pos = float4(v.center, 0, 1);
  v.tally = float2(1, (vertex + 1) * (instance + 1) + data.y);
  return v;
}
void quad(V v, inout TriangleStream<V> stream) {
  for (uint i = 0; i < 4; i++) {
    v.pos = float4(v.center + float2(i & 1 ? 1 : -1, i & 2 ? -1 : 1) / float2(WIDTH, HEIGHT), 0, 1);
    stream.Append(v);
  }
}
#if !TESS
[maxvertexcount(4)]
#if PATCH
void gs(InputPatch<V, CORNERS> vertices, uint primitive : SV_PrimitiveID, inout TriangleStream<V> stream) {
#else
void gs(INPUT V vertices[CORNERS], uint primitive : SV_PrimitiveID, inout TriangleStream<V> stream) {
#endif
  V v = vertices[0];
  v.tally = float2(1, 0);
  for (uint i = 0; i < CORNERS; i++)
    v.tally.y += vertices[i].tally.y;
  v.tally.y *= primitive + 1;
  quad(v, stream);
}
#endif
[maxvertexcount(4)]
void gs_tess(triangle V vertices[3], inout TriangleStream<V> stream) {
  quad(vertices[0], stream);
}
#if TESS
struct F {
  float edges[4] : SV_TessFactor;
  float inside[2] : SV_InsideTessFactor;
  float value : VALUE;
};
F factors(InputPatch<V, CORNERS> patch) {
  F f;
  f.edges[0] = f.edges[1] = f.edges[2] = f.edges[3] = 1;
  f.inside[0] = f.inside[1] = 1;
  f.value = 0;
  for (uint i = 0; i < CORNERS; i++)
    f.value += patch[i].tally.y;
  return f;
}
[domain("quad")]
[partitioning("integer")]
[outputtopology("triangle_cw")]
[outputcontrolpoints(1)]
[patchconstantfunc("factors")]
[maxtessfactor(1)]
V hs(InputPatch<V, CORNERS> patch) { return patch[0]; }
[domain("quad")]
V ds(F f, float2 uv : SV_DomainLocation, const OutputPatch<V, 1> patch, uint primitive : SV_PrimitiveID) {
  V v = patch[0];
  v.pos = float4(v.center + (uv * 2 - 1) / float2(WIDTH, HEIGHT), 0, 1);
  v.tally = float2(1, f.value * (primitive + 1));
  return v;
}
#endif
float2 ps(V v) : SV_Target { return v.tally; }
)hlsl";

int
main() {
  step("create the device, shaders and pixel readback");
  ComPtr<ID3D11Device> device;
  ComPtr<ID3D11DeviceContext> immediate, deferred;
  const D3D_FEATURE_LEVEL level = D3D_FEATURE_LEVEL_11_0;
  CHECK(D3D11CreateDevice(
      nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0, &level, 1, D3D11_SDK_VERSION, &device, nullptr, &immediate
  ));
  CHECK(device->CreateDeferredContext(0, &deferred));
  const UINT width = 3, instance_count = 3, first_instance = 2, height = first_instance + instance_count;
  const std::vector<std::string> defines = {
      "WIDTH=" + std::to_string(width), "HEIGHT=" + std::to_string(height), "TESS=1", "INPUT=point", "CORNERS=1"
  };
  auto vs_code = compile(hlsl, "vs", "vs", defines), ps_code = compile(hlsl, "ps", "ps", defines);
  auto ds_code = compile(hlsl, "ds", "ds", defines), gs_tess_code = compile(hlsl, "gs_tess", "gs", defines);
  if (!expect(vs_code && ps_code && ds_code && gs_tess_code, "HLSL did not compile"))
    return verdict();
  ComPtr<ID3D11VertexShader> vs;
  ComPtr<ID3D11PixelShader> ps;
  ComPtr<ID3D11DomainShader> ds;
  ComPtr<ID3D11GeometryShader> gs_tess;
  CHECK(device->CreateVertexShader(vs_code->GetBufferPointer(), vs_code->GetBufferSize(), nullptr, &vs));
  CHECK(device->CreatePixelShader(ps_code->GetBufferPointer(), ps_code->GetBufferSize(), nullptr, &ps));
  CHECK(device->CreateDomainShader(ds_code->GetBufferPointer(), ds_code->GetBufferSize(), nullptr, &ds));
  CHECK(device->CreateGeometryShader(
      gs_tess_code->GetBufferPointer(), gs_tess_code->GetBufferSize(), nullptr, &gs_tess
  ));
  ComPtr<ID3D11ShaderReflection> reflection;
  CHECK(D3DReflect(
      vs_code->GetBufferPointer(), vs_code->GetBufferSize(), IID_ID3D11ShaderReflection,
      reinterpret_cast<void **>(reflection.GetAddressOf())
  ));
  D3D11_SHADER_DESC shader_desc{};
  CHECK(reflection->GetDesc(&shader_desc));
  UINT registers = 0;
  for (UINT i = 0; i < shader_desc.OutputParameters; i++) {
    D3D11_SIGNATURE_PARAMETER_DESC output{};
    CHECK(reflection->GetOutputParameterDesc(i, &output));
    registers = std::max(registers, output.Register + 1);
  }
  const D3D11_INPUT_ELEMENT_DESC elements[] = {
      {"POSITION", 0, DXGI_FORMAT_R32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"INSTANCE", 0, DXGI_FORMAT_R32G32_FLOAT, 1, 0, D3D11_INPUT_PER_INSTANCE_DATA, 1}
  };
  ComPtr<ID3D11InputLayout> layout;
  CHECK(device->CreateInputLayout(
      elements, std::size(elements), vs_code->GetBufferPointer(), vs_code->GetBufferSize(), &layout
  ));
  float positions[width], instances[height][2];
  for (UINT x = 0; x < width; x++)
    positions[x] = (x + 0.5f) / width * 2 - 1;
  for (UINT y = 0; y < height; y++) {
    instances[y][0] = 1 - (y + 0.5f) / height * 2;
    instances[y][1] = float(y + 1);
  }
  ComPtr<ID3D11Buffer> vertices, instance_data, arguments;
  D3D11_BUFFER_DESC vertex_desc{sizeof(positions), D3D11_USAGE_IMMUTABLE, D3D11_BIND_VERTEX_BUFFER};
  D3D11_SUBRESOURCE_DATA initial{positions};
  CHECK(device->CreateBuffer(&vertex_desc, &initial, &vertices));
  vertex_desc.ByteWidth = sizeof(instances);
  initial.pSysMem = instances;
  CHECK(device->CreateBuffer(&vertex_desc, &initial, &instance_data));
  D3D11_BUFFER_DESC argument_desc{
      2 * sizeof(D3D11_DRAW_INDEXED_INSTANCED_INDIRECT_ARGS), D3D11_USAGE_DEFAULT, 0, 0,
      D3D11_RESOURCE_MISC_DRAWINDIRECT_ARGS
  };
  CHECK(device->CreateBuffer(&argument_desc, nullptr, &arguments));
  ComPtr<ID3D11Texture2D> target, staging;
  ComPtr<ID3D11RenderTargetView> rtv;
  D3D11_TEXTURE2D_DESC texture_desc{
      width, height, 1, 1, DXGI_FORMAT_R32G32_FLOAT, {1, 0}, D3D11_USAGE_DEFAULT, D3D11_BIND_RENDER_TARGET
  };
  CHECK(device->CreateTexture2D(&texture_desc, nullptr, &target));
  CHECK(device->CreateRenderTargetView(target.Get(), nullptr, &rtv));
  texture_desc.Usage = D3D11_USAGE_STAGING;
  texture_desc.BindFlags = 0;
  texture_desc.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
  CHECK(device->CreateTexture2D(&texture_desc, nullptr, &staging));
  D3D11_BLEND_DESC blend_desc{};
  blend_desc.RenderTarget[0] = {
      TRUE, D3D11_BLEND_ONE, D3D11_BLEND_ONE, D3D11_BLEND_OP_ADD, D3D11_BLEND_ONE, D3D11_BLEND_ONE,
      D3D11_BLEND_OP_ADD, D3D11_COLOR_WRITE_ENABLE_ALL
  };
  ComPtr<ID3D11BlendState> blend;
  CHECK(device->CreateBlendState(&blend_desc, &blend));
  D3D11_RASTERIZER_DESC raster_desc{D3D11_FILL_SOLID, D3D11_CULL_NONE};
  raster_desc.DepthClipEnable = TRUE;
  ComPtr<ID3D11RasterizerState> raster;
  CHECK(device->CreateRasterizerState(&raster_desc, &raster));

  struct Topology {
    D3D11_PRIMITIVE_TOPOLOGY value;
    const char *input;
    UINT corners, advance;
    bool strip;
  };
  // the vertex counts and strip increments are those of D3D11.3 8.6.2 and 8.10.
  const Topology geometry[] = {
      {D3D11_PRIMITIVE_TOPOLOGY_POINTLIST, "point", 1, 1, false},
      {D3D11_PRIMITIVE_TOPOLOGY_LINELIST, "line", 2, 2, false},
      {D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP, "line", 2, 1, true},
      {D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST, "triangle", 3, 3, false},
      {D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP, "triangle", 3, 1, true},
      {D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ, "lineadj", 4, 4, false},
      {D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ, "lineadj", 4, 1, true},
      {D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ, "triangleadj", 6, 6, false},
      {D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ, "triangleadj", 6, 2, true}
  };
  for (UINT stages : {0, 1, 2, 3}) {
    const bool tessellation = stages == 1 || stages == 2;
    std::vector<Topology> topologies(std::begin(geometry), std::end(geometry));
    if (tessellation)
      topologies.clear();
    for (UINT t = D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST;
         t <= D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST; t++) {
      const UINT corners = t - D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST + 1;
      topologies.push_back({D3D11_PRIMITIVE_TOPOLOGY(t), "InputPatch", corners, corners, false});
    }
    for (auto topology : topologies) {
      step("compile stages %u, topology %u", stages, topology.value);
      auto shader_defines = defines;
      shader_defines[2] = "TESS=" + std::to_string(tessellation);
      shader_defines.back() = "CORNERS=" + std::to_string(topology.corners);
      shader_defines[shader_defines.size() - 2] = std::string("INPUT=") + topology.input;
      shader_defines.push_back(
          "PATCH=" + std::to_string(topology.value >= D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST)
      );
      auto code = compile(hlsl, tessellation ? "hs" : "gs", tessellation ? "hs" : "gs", shader_defines);
      if (!expect(bool(code), "HLSL did not compile"))
        return verdict();
      ComPtr<ID3D11GeometryShader> gs;
      ComPtr<ID3D11HullShader> hs;
      if (tessellation) {
        CHECK(device->CreateHullShader(code->GetBufferPointer(), code->GetBufferSize(), nullptr, &hs));
      } else if (stages == 3) {
        const D3D11_SO_DECLARATION_ENTRY entries[] = {{0, "TALLY", 0, 0, 2, 0}};
        const UINT stride = sizeof(float[2]);
        CHECK(device->CreateGeometryShaderWithStreamOutput(
            code->GetBufferPointer(), code->GetBufferSize(), entries, std::size(entries), &stride, 1, 0, nullptr, &gs
        ));
      } else {
        CHECK(device->CreateGeometryShader(code->GetBufferPointer(), code->GetBufferSize(), nullptr, &gs));
      }

      std::vector<UINT> counts{0, 1};
      if (tessellation) {
        // fork phases and payload size can reduce the tessellation group; cover each power-of-two boundary.
        for (UINT group = 1; group <= SM50_GEOMETRY_WARP_THREADS; group *= 2)
          counts.insert(counts.end(), {group - 1, group, group + 1, 2 * group + 1});
      } else {
        const UINT group = SM50GeometryWarp(topology.corners, topology.strip, registers).primitives;
        if (!expect(group > 0, "no primitive fits an object threadgroup"))
          return verdict();
        counts.insert(counts.end(), {group - 1, group, group + 1, 2 * group + 1});
      }
      std::sort(counts.begin(), counts.end());
      counts.erase(std::unique(counts.begin(), counts.end()), counts.end());
      const UINT start_index = 4, offset_indices = 3;
      std::vector<D3D11_DRAW_INDEXED_INSTANCED_INDIRECT_ARGS> draws = {
          {topology.corners, 0, start_index, 0, first_instance}
      };
      for (UINT indices = 1; indices < topology.corners; indices++)
        draws.push_back({indices, instance_count, start_index, 0, first_instance});
      for (UINT count : counts) {
        const UINT indices = !count ? 0 : topology.strip ? (count - 1) * topology.advance + topology.corners
                                                        : count * topology.corners;
        draws.push_back({indices, instance_count, start_index, 0, first_instance});
      }
      const UINT indices = draws.back().IndexCountPerInstance + start_index + offset_indices;
      std::vector<UINT16> words16(indices, 1);
      std::vector<UINT> words32(indices, 1);
      std::fill_n(words16.begin(), start_index + offset_indices, 0);
      std::fill_n(words32.begin(), start_index + offset_indices, 0);
      ComPtr<ID3D11Buffer> ib16, ib32;
      D3D11_BUFFER_DESC index_desc{
          UINT(words16.size() * sizeof(words16[0])), D3D11_USAGE_IMMUTABLE, D3D11_BIND_INDEX_BUFFER
      };
      initial.pSysMem = words16.data();
      CHECK(device->CreateBuffer(&index_desc, &initial, &ib16));
      index_desc.ByteWidth = words32.size() * sizeof(words32[0]);
      initial.pSysMem = words32.data();
      CHECK(device->CreateBuffer(&index_desc, &initial, &ib32));
      struct Binding {
        ID3D11Buffer *buffer;
        DXGI_FORMAT format;
      };
      const Binding bindings[] = {
          {nullptr, DXGI_FORMAT_UNKNOWN}, {ib16.Get(), DXGI_FORMAT_R16_UINT}, {nullptr, DXGI_FORMAT_R16_UINT},
          {ib32.Get(), DXGI_FORMAT_R32_UINT}, {nullptr, DXGI_FORMAT_R32_UINT}
      };
      for (auto context : {immediate.Get(), deferred.Get()}) {
        context->IASetInputLayout(layout.Get());
        ID3D11Buffer *buffers[] = {vertices.Get(), instance_data.Get()};
        const UINT strides[] = {sizeof(positions[0]), sizeof(instances[0])}, offsets[] = {0, 0};
        context->IASetVertexBuffers(0, std::size(buffers), buffers, strides, offsets);
        context->VSSetShader(vs.Get(), nullptr, 0);
        context->GSSetShader(stages == 2 ? gs_tess.Get() : gs.Get(), nullptr, 0);
        context->HSSetShader(hs.Get(), nullptr, 0);
        context->DSSetShader(tessellation ? ds.Get() : nullptr, nullptr, 0);
        context->PSSetShader(ps.Get(), nullptr, 0);
        context->RSSetState(raster.Get());
        const D3D11_VIEWPORT viewport{0, 0, float(width), float(height), 0, 1};
        context->RSSetViewports(1, &viewport);
        context->OMSetRenderTargets(1, rtv.GetAddressOf(), nullptr);
        context->OMSetBlendState(blend.Get(), nullptr, ~0u);
        context->IASetPrimitiveTopology(topology.value);
        for (auto binding : bindings)
          for (INT base : {0, 1})
            for (UINT call : {0, 1, 2})
              for (auto draw : draws) {
                draw.BaseVertexLocation = base;
                if (!call) {
                  draw.InstanceCount = 1;
                  draw.StartInstanceLocation = 0;
                }
                const UINT index_size = binding.format == DXGI_FORMAT_R32_UINT ? sizeof(UINT) : sizeof(UINT16);
                context->IASetIndexBuffer(binding.buffer, binding.format, offset_indices * index_size);
                step(
                    "%s, stages %u, topology %u, %s, format %u, call %u, indices %u, base %d, instances %u from %u",
                    context == immediate.Get() ? "immediate" : "deferred", stages, topology.value,
                    binding.buffer ? "bound" : "null", binding.format, call, draw.IndexCountPerInstance, base,
                    draw.InstanceCount, draw.StartInstanceLocation
                );
                const float clear[4] = {};
                context->ClearRenderTargetView(rtv.Get(), clear);
                if (!call)
                  context->DrawIndexed(draw.IndexCountPerInstance, draw.StartIndexLocation, base);
                else if (call == 1)
                  context->DrawIndexedInstanced(
                      draw.IndexCountPerInstance, draw.InstanceCount, draw.StartIndexLocation, base,
                      draw.StartInstanceLocation
                  );
                else {
                  const D3D11_DRAW_INDEXED_INSTANCED_INDIRECT_ARGS records[] = {{}, draw};
                  context->UpdateSubresource(arguments.Get(), 0, nullptr, records, 0, 0);
                  context->DrawIndexedInstancedIndirect(arguments.Get(), sizeof(records[0]));
                }
                context->CopyResource(staging.Get(), target.Get());
                if (context == deferred.Get()) {
                  ComPtr<ID3D11CommandList> list;
                  CHECK(context->FinishCommandList(TRUE, &list));
                  immediate->ExecuteCommandList(list.Get(), TRUE);
                }
                D3D11_MAPPED_SUBRESOURCE mapped;
                CHECK(immediate->Map(staging.Get(), 0, D3D11_MAP_READ, 0, &mapped));
                const UINT primitives =
                    draw.IndexCountPerInstance < topology.corners ? 0
                    : topology.strip ? (draw.IndexCountPerInstance - topology.corners) / topology.advance + 1
                                     : draw.IndexCountPerInstance / topology.corners;
                const UINT copies = stages == 2 ? 2 : 1, index = binding.buffer ? 1 : 0;
                for (UINT y = 0; y < height; y++)
                  for (UINT x = 0; x < width; x++) {
                    const bool drawn = x == UINT(base) + index && y >= draw.StartInstanceLocation &&
                                       y - draw.StartInstanceLocation < draw.InstanceCount;
                    const float count = drawn ? primitives * copies : 0;
                    const float vertex_value = (index + 1) * (y - draw.StartInstanceLocation + 1) + instances[y][1];
                    const float value =
                        drawn ? copies * topology.corners * primitives * (primitives + 1) / 2 * vertex_value : 0;
                    const float *got = (const float *)((const char *)mapped.pData + y * mapped.RowPitch) + 2 * x;
                    expect(got[0] == count && got[1] == value, "pixel %u,%u is %g,%g, want %g,%g", x, y,
                           got[0], got[1], count, value);
                  }
                immediate->Unmap(staging.Get(), 0);
              }
      }
    }
  }
  return verdict();
}
