// contract: each primitive's ID starts at zero within its instance, including the interior primitives of adjacency
// topologies. "PrimitiveID starts at 0 for the first primitive generated by a Draw*() call, and increments for each
// subsequent primitive. When Draw*Instanced() is used, the PrimitiveID resets to its starting value whenever a new
// instance begins in the set of instances produced by the call." (D3D11.3 8.17). "the PrimitiveID is only maintained
// for the interior primitives in the topology (the non-adjacent primitives), just like the set of primitives in a
// triangle strip without adjacency." (8.17). strip cuts restart assembly, not PrimitiveID (8.6.2 pseudocode).
// every primitive covers one pixel, whose value must be its ID plus one; instances have separate rows. the geometry
// and topology data are those of ../assembly.hpp, with positive cull distances and no stream output.
#include "d3d11_test.hpp"
#include "../assembly.hpp"
#include "../../src/airconv/airconv_public.h"

static const char hlsl[] = R"hlsl(
cbuffer Case : register(b0) { uint corners, strip, stride, first, every, last, primitives, run_vertices; };
struct O {
  float4 pos : SV_Position;
#if CULL
  float cull : SV_CullDistance;
#endif
};
O vs(uint id : SV_VertexID, uint instance : SV_InstanceID) {
  uint run = id / run_vertices;
  id %= run_vertices;
  uint k = strip ? id : id % stride, c = (k - first) / every, n = strip ? c : id / stride;
  bool own = k >= first && (k - first) % every == 0 && (strip ? id <= last : c < corners);
  float2 pixels;
  if (!own)
    pixels = float2(id + 0.5, 2 * instance + 1.5);
  else if (corners == 1)
    pixels = float2(n + 0.5, 2 * instance + 0.5);
  else if (corners == 2)
    pixels = float2(n + (strip ? 0 : c) + 0.25, 2 * instance + 0.5);
  else if (strip)
    pixels = float2(n + 0.5, 2 * instance + (n % 2 ? 0.9 : 0.1));
  else
    pixels = float2(n + (c == 1 ? 1.4 : 0), 2 * instance + (c == 2 ? 1.4 : 0));
  pixels.x += run * primitives;
  O o;
  o.pos = float4(pixels / float2(WIDTH, HEIGHT) * float2(2, -2) + float2(-1, 1), 0, 1);
#if CULL
  o.cull = 1;
#endif
  return o;
}
uint ps(uint id : SV_PrimitiveID) : SV_Target { return id + 1; }
)hlsl";

int main() {
  step("create the device, shaders and readback target");
  ComPtr<ID3D11Device> device;
  ComPtr<ID3D11DeviceContext> context;
  const D3D_FEATURE_LEVEL level = D3D_FEATURE_LEVEL_11_0;
  CHECK(D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0, &level, 1, D3D11_SDK_VERSION, &device, nullptr,
                          &context));
  const UINT max_instances = 3, width = 4 * SM50_GEOMETRY_WARP_THREADS + 2, height = 2 * max_instances;
  ComPtr<ID3D11VertexShader> vertex[2];
  ComPtr<ID3D11PixelShader> pixel;
  for (bool cull : {false, true}) {
    auto vs =
        compile(hlsl, "vs", "vs",
                {"WIDTH=" + std::to_string(width), "HEIGHT=" + std::to_string(height), "CULL=" + std::to_string(cull)});
    if (!expect(!!vs, "vertex shader did not compile"))
      return verdict();
    CHECK(device->CreateVertexShader(vs->GetBufferPointer(), vs->GetBufferSize(), nullptr, &vertex[cull]));
  }
  auto ps = compile(hlsl, "ps", "ps", {"WIDTH=" + std::to_string(width), "HEIGHT=" + std::to_string(height), "CULL=0"});
  if (!expect(!!ps, "pixel shader did not compile"))
    return verdict();
  CHECK(device->CreatePixelShader(ps->GetBufferPointer(), ps->GetBufferSize(), nullptr, &pixel));
  struct Constants {
    UINT corners, strip, stride, first, every, last, primitives, run_vertices;
  };
  D3D11_BUFFER_DESC constants_desc{sizeof(Constants), D3D11_USAGE_DEFAULT, D3D11_BIND_CONSTANT_BUFFER};
  ComPtr<ID3D11Buffer> constants;
  CHECK(device->CreateBuffer(&constants_desc, nullptr, &constants));
  D3D11_TEXTURE2D_DESC texture_desc{
      width, height, 1, 1, DXGI_FORMAT_R32_UINT, {1, 0}, D3D11_USAGE_DEFAULT, D3D11_BIND_RENDER_TARGET};
  ComPtr<ID3D11Texture2D> target, readback;
  ComPtr<ID3D11RenderTargetView> rtv;
  CHECK(device->CreateTexture2D(&texture_desc, nullptr, &target));
  CHECK(device->CreateRenderTargetView(target.Get(), nullptr, &rtv));
  texture_desc.Usage = D3D11_USAGE_STAGING;
  texture_desc.BindFlags = 0;
  texture_desc.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
  CHECK(device->CreateTexture2D(&texture_desc, nullptr, &readback));
  D3D11_RASTERIZER_DESC raster_desc{D3D11_FILL_SOLID, D3D11_CULL_NONE};
  raster_desc.DepthClipEnable = TRUE;
  ComPtr<ID3D11RasterizerState> raster;
  CHECK(device->CreateRasterizerState(&raster_desc, &raster));
  D3D11_VIEWPORT viewport{0, 0, (float)width, (float)height, 0, 1};
  context->RSSetState(raster.Get());
  context->RSSetViewports(1, &viewport);
  context->OMSetRenderTargets(1, rtv.GetAddressOf(), nullptr);
  context->VSSetConstantBuffers(0, 1, constants.GetAddressOf());
  context->PSSetShader(pixel.Get(), nullptr, 0);

  for (auto &c : assembly::cases) {
    UINT per_primitive = c.strip ? c.corners * c.every + 2 * c.first : c.stride;
    // the position and optional scalar cull distance fit the full object warp
    auto warp = SM50GeometryWarp(per_primitive, c.strip, 0);
    for (UINT primitives : {3u, warp.primitives - 1, warp.primitives, warp.primitives + 1, 2 * warp.primitives + 1})
      for (bool cull : {false, true})
        for (DXGI_FORMAT format : {DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16_UINT, DXGI_FORMAT_R32_UINT})
          for (bool indirect : {false, true})
            for (UINT instances : {1u, max_instances})
              for (bool cuts : {false, true}) {
                bool indexed = format != DXGI_FORMAT_UNKNOWN;
                if (cuts && (!indexed || !c.strip))
                  continue;
                step("topology %u, %u primitives, cull %u, index format %u, indirect %u, %u instances, cuts %u",
                     c.topology, primitives, cull, format, indirect, instances, cuts);
                UINT vertices = c.strip ? (primitives - 1) * c.every + per_primitive : primitives * c.stride;
                Constants values{c.corners,  c.strip, c.stride,
                                 c.first,    c.every, c.first + (primitives + c.corners - 2) * c.every,
                                 primitives, vertices};
                context->UpdateSubresource(constants.Get(), 0, nullptr, &values, 0, 0);
                context->VSSetShader(vertex[cull].Get(), nullptr, 0);
                context->IASetPrimitiveTopology(c.topology);
                ComPtr<ID3D11Buffer> indices;
                std::vector<UINT> words;
                UINT cut = format == DXGI_FORMAT_R16_UINT ? UINT16_MAX : UINT32_MAX;
                if (cuts)
                  words.push_back(cut);
                for (UINT run = 0; run < (cuts ? 2u : 1u); run++) {
                  for (UINT i = 0; i < vertices; i++)
                    words.push_back(run * vertices + i);
                  if (cuts)
                    words.insert(words.end(), {cut, cut});
                }
                UINT count = indexed ? (UINT)words.size() : vertices;
                if (indexed) {
                  std::vector<UINT16> narrow(words.begin(), words.end());
                  D3D11_BUFFER_DESC desc{UINT(count * (format == DXGI_FORMAT_R16_UINT ? sizeof(UINT16) : sizeof(UINT))),
                                         D3D11_USAGE_IMMUTABLE, D3D11_BIND_INDEX_BUFFER};
                  D3D11_SUBRESOURCE_DATA data{format == DXGI_FORMAT_R16_UINT ? (const void *)narrow.data()
                                                                             : words.data()};
                  CHECK(device->CreateBuffer(&desc, &data, &indices));
                }
                context->IASetIndexBuffer(indices.Get(), format, 0);
                const float clear[4] = {};
                context->ClearRenderTargetView(rtv.Get(), clear);
                if (indirect) {
                  D3D11_DRAW_INSTANCED_INDIRECT_ARGS draw{count, instances};
                  D3D11_DRAW_INDEXED_INSTANCED_INDIRECT_ARGS draw_indexed{count, instances};
                  D3D11_BUFFER_DESC desc{UINT(indexed ? sizeof(draw_indexed) : sizeof(draw)), D3D11_USAGE_IMMUTABLE, 0,
                                         0, D3D11_RESOURCE_MISC_DRAWINDIRECT_ARGS};
                  D3D11_SUBRESOURCE_DATA data{indexed ? (const void *)&draw_indexed : &draw};
                  ComPtr<ID3D11Buffer> arguments;
                  CHECK(device->CreateBuffer(&desc, &data, &arguments));
                  if (indexed)
                    context->DrawIndexedInstancedIndirect(arguments.Get(), 0);
                  else
                    context->DrawInstancedIndirect(arguments.Get(), 0);
                } else if (indexed) {
                  if (instances == 1)
                    context->DrawIndexed(count, 0, 0);
                  else
                    context->DrawIndexedInstanced(count, instances, 0, 0, 0);
                } else if (instances == 1)
                  context->Draw(count, 0);
                else
                  context->DrawInstanced(count, instances, 0, 0);
                context->CopyResource(readback.Get(), target.Get());
                D3D11_MAPPED_SUBRESOURCE mapped;
                CHECK(context->Map(readback.Get(), 0, D3D11_MAP_READ, 0, &mapped));
                for (UINT y = 0; y < height; y++)
                  for (UINT x = 0; x < width; x++) {
                    UINT id = x - (c.strip && c.corners == 3);
                    UINT want = !(y % 2) && y / 2 < instances && id < primitives * (cuts ? 2 : 1) ? id + 1 : 0;
                    UINT got = reinterpret_cast<const UINT *>((const char *)mapped.pData + y * mapped.RowPitch)[x];
                    expect(got == want, "pixel %u,%u: %u, want %u", x, y, got, want);
                  }
                context->Unmap(readback.Get(), 0);
              }
  }
  return verdict();
}
